### ISSUE TITLE
put ireland on the map

### ISSUE THREAD

**Issue by josefkreitmayer** [susy-partners/transformap-viewer#19]
Somehow we seem to have lost communication there. Will reproduce the communication and bring it up to speed again, to bring Ireland on the map.

>Post codes and house numbers would be used in cities, but in rural Ireland house names and parts of a county are more common. I will let you know how I get on with the logo permissions but can't see that there would be a problem.

**Comment by josefkreitmayer** [comment]
copyrighted images to include for:

- [x] Dunhill Eco Park, 

- [ ] Creative Consultants, 
- [x] Cill Barra Sports, 
- [ ] Ballybeg Greens, 
- [x] GIY International, 
- [ ] Waterford Suir Valley Railway


Further stuff to do:
- ods broken (starts with line 23)
- 8 entries
- last one does not have coordinates
- csv to umap 
- ods - table for export

**Comment by species** [comment]
Ireland is on the map.
